### ISSUE TITLE
NPE when running "mvn clean test -Dtest=MyStories"

### ISSUE THREAD

**Issue by mfriedenhagen** [valfirst/jbehave-junit-runner#10]
Hello,

I am using Netbeans which is delegating test runs to Maven/Surefire directly, so in the end it boils down to a call as mentioned in the title. 

`mvn clean test -Dtest=MyStories`

Now I am getting:

```
-------------------------------------------------------------------------------
Test set: de.friedenhagen.jbehavesimple.MyStories
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.338 sec <<< FAILURE!
de.friedenhagen.jbehavesimple.MyStories  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException
    at de.codecentric.jbehave.junit.monitoring.JUnitScenarioReporter.<init>(JUnitScenarioReporter.java:55)
    at de.codecentric.jbehave.junit.monitoring.JUnitReportingRunner.run(JUnitReportingRunner.java:80)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
```

You may easily reproduce this by cloning git://github.com/mfriedenhagen/jbehave-simple.git and running `mvn clean test -Dtest=MyStories`.

**Comment by AndreasEK** [comment]
Hi,

could you please try with the latest snapshot? At least in my tests, the bug is now fixed. Thanks for reporting! 

You can either download the jar from the download section, or point maven to the snapshot release, and pull version 1.0.1-SNAPSHOT:
https://oss.sonatype.org/content/repositories/snapshots/de/codecentric/jbehave-junit-runner/

**Comment by mfriedenhagen** [comment]
Thanks, this did work with my sample-project :-).

**Comment by AndreasEK** [comment]
Great, thank you. If you have further issues or ideas, please let us know :)
