### ISSUE TITLE
I cannot start single scenario in eclipse

### ISSUE THREAD

**Issue by javadev** [valfirst/jbehave-junit-runner#157]
![screenshot_193](https://user-images.githubusercontent.com/348496/48768821-6f4a1b80-ecba-11e8-9364-fa7429dd7965.png)

![screenshot_194](https://user-images.githubusercontent.com/348496/48768840-7709c000-ecba-11e8-894a-a90d7297f09c.png)

The error message:

```
java.lang.Exception: No tests found matching [{ExactMatcher:fDisplayName=Scenario: 2 squared], {ExactMatcher:fDisplayName=Scenario: 2 squared(com.github.valfirst.jbehave.junit.monitoring.ExampleScenarioJUnitStory)]] from org.junit.internal.requests.ClassRequest@566776ad
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createFilteredTest(JUnit4TestLoader.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:74)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:525)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

```

Please help me to configure eclipse or Story file

**Comment by valfirst** [comment]
`jbehave-junit-runner` just shows the execution of JBehave stories, it doesn't allow to choose scenarios to run from the UI, use JBehave configuration for that purpose

**Comment by javadev** [comment]
@valfirst Thank you for feedback. Please send me a link with JBehave configuration examples.

**Comment by valfirst** [comment]
@javadev  http://lmgtfy.com/?q=jbehave+configuration

**Comment by javadev** [comment]
@valfirst Thank you for google link. I tried to start single scenarion from this repository.

Could you help me to execute ExampleScenarioJUnitStory/Scenario: 2 squared in Eclipse?
Which configuration do I need to add?

**Comment by valfirst** [comment]
@javadev https://jbehave.org/reference/stable/meta-filtering.html
