### ISSUE TITLE
FailingUponPendingStep strategy causes a RuntimeException

### ISSUE THREAD

**Issue by alexbepple** [valfirst/jbehave-junit-runner#22]
Configuring JBehave to fail on pending steps causes a RuntimeException in 1.0.1.

``` Java
@RunWith(JUnitReportingRunner.class)
public class Foobar extends JUnitStory {
    @Override
    public Configuration configuration() {
        return super.configuration().usePendingStepStrategy(new FailingUponPendingStep());
    }
}
```

``` Java
java.lang.RuntimeException: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
foo/foobar.story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: foo/foobar.story
    at de.codecentric.jbehave.junit.monitoring.JUnitReportingRunner.run(JUnitReportingRunner.java:81)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
foo/foobar.story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: foo/foobar.story
    at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:495)
    at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:224)
    at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:205)
    at de.codecentric.jbehave.junit.monitoring.JUnitReportingRunner.run(JUnitReportingRunner.java:79)
    ... 6 more
```

**Comment by AndreasEK** [comment]
Hi Alex,

when you have pending steps, and tell JBehave to fail on pending steps, this is the expected behaviour. As you see from the stacktrace, the exception is thrown in the StoryManager. To verify, try the same scenario without the jbehave-junit-runner. The result should be the same.

There's a little utility method you can use to configure the embedder to work smoothly (in my experience):

JUnitReportingRunner.recommandedControls(configuredEmbedder());
