### ISSUE TITLE
NullPointerException when running stories without an initial description

### ISSUE THREAD

**Issue by kappolo** [valfirst/jbehave-junit-runner#28]
Hi everyone,

I just wanted to let you know that I find something a bit odd (perhaps considerable as a bug?) when using jbehave-junit-runner 1.0.1.
If any story file doesn't contain an initial description before the first scenario definition, the test fails during initialization with the following stacktrace:

Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=false,ignoreFailureInView=false,verboseFailures=false,verboseFiltering=false,storyTimeoutInSecs=300,threads=1]
Generating reports view to '/home/user/project/target/jbehave' using formats '[stats, console, txt, junitscenarioreporter]' and view properties '{defaultFormats=stats, decorateNonHtml=true, viewDirectory=view, decorated=ftl/jbehave-report-decorated.ftl, reports=ftl/jbehave-reports-with-totals.ftl, maps=ftl/jbehave-maps.ftl, navigator=ftl/jbehave-navigator.ftl, views=ftl/jbehave-views.ftl, nonDecorated=ftl/jbehave-report-non-decorated.ftl}'
Reports view generated with 2 stories (of which 0 pending) containing 16 scenarios (of which 0 pending)
java.lang.RuntimeException: java.lang.NullPointerException
    at de.codecentric.jbehave.junit.monitoring.JUnitReportingRunner.run(JUnitReportingRunner.java:81)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.NullPointerException
    at de.codecentric.jbehave.junit.monitoring.JUnitScenarioReporter.beforeStory(JUnitScenarioReporter.java:84)
    at org.jbehave.core.reporters.DelegatingStoryReporter.beforeStory(DelegatingStoryReporter.java:67)
    at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStory(ConcurrentStoryReporter.java:107)
    at org.jbehave.core.embedder.StoryRunner.runBeforeOrAfterStories(StoryRunner.java:70)
    at org.jbehave.core.embedder.StoryManager.runBeforeOrAfterStories(StoryManager.java:91)
    at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:75)
    at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:202)
    at de.codecentric.jbehave.junit.monitoring.JUnitReportingRunner.run(JUnitReportingRunner.java:79)
    ... 6 more

Looking up at JUnitScenarioReporter.java:84 I've found out that a description is necessary.
I would propose a fix myself but since I don't have currently the time to run through the whole code, I'm just signaling it :)

Btw, it looks like the problem doesn't appear if you are running a JUnitStory instead of JUnitStories, but I don't have time now to reproduce the thing.

Thanks!

**Comment by BrunoChauvet** [comment]
I am currently facing the same problem as we are creating empty story files as placeholders which makes our build process to fail.
