### ISSUE TITLE
Wrong number of steps is reported, steps are repeated

### ISSUE THREAD

**Issue by nasalp** [valfirst/jbehave-junit-runner#48]
Junit doesnt display full details of scenarios/steps executed.
11 scenarios are reported although only 2 are actually defined.
Using intellijJ 13.1.2
![jbehave](https://cloud.githubusercontent.com/assets/7673400/3060066/bbf9ac88-e1f3-11e3-9365-36f0eb8dc99d.JPG)

Source project: https://www.dropbox.com/s/yg4tldm90xbgs5s/jbeh1.rar
I was able to reproduce on two machines. I create the projects using Maven Archetypes, so maybe there is the issue.

**Comment by skurlow** [comment]
I haven't downloaded your project but I wonder does it help you if you do not hide the passed tests??? You have the Hide Passed tests option turned on in the top left hand corner of your screen shot.

Also can you provide the full text in the console? It seems like the runner is running your same my.story at least 3 times.

**Comment by nasalp** [comment]
Toggling the Hide Passed certainly helped, so we can assume the issue is resolved.
But still the console output doesn't seem "right", as if all scenarios were executed concurrently
:
Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=true,ignoreFailureInView=true,verboseFailures=false,verboseFiltering=false,storyTimeoutInSecs=60,threads=2]

(BeforeStories)

Running story stories/my.story

(stories/my.story)
Scenario: 2 squared
Given a variable x with value 2
Given a variable x with value 2
Given a variable x with value 2
When I multiply x by 2
When I multiply x by 2
When I multiply x by 2
Then x should equal 4
Then x should equal 4
Then x should equal 4

Scenario: 3 squared
Scenario: 3 squared
Scenario: 3 squared
Given a variable x with value 3
Given a variable x with value 3
Given a variable x with value 3
When I multiply x by 3
When I multiply x by 3
When I multiply x by 3
Then x should equal 10 (FAILED)
Then x should equal 10 (FAILED)
Then x should equal 10 (FAILED)
(java.lang.RuntimeException: x is 9, but should be 10)
(java.lang.RuntimeException: x is 9, but should be 10)
(java.lang.RuntimeException: x is 9, but should be 10)

java.lang.RuntimeException: x is 9, but should be 10
    at behave_test1.steps.MySteps.thenXshouldBe(MySteps.java:21)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.jbehave.core.steps.StepCreator$ParameterisedStep.perform(StepCreator.java:550)
    at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:531)
    at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:511)
    at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:475)
    at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:308)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Scenario: 5 squared
Scenario: 5 squared
Scenario: 5 squared
Given a variable x with value 4
Given a variable x with value 4
Given a variable x with value 4
When I multiply x by 4
When I multiply x by 4
When I multiply x by 4
Then x should equal 10 (FAILED)
Then x should equal 10 (FAILED)
Then x should equal 10 (FAILED)
(java.lang.RuntimeException: x (java.lang.RuntimeException: x (java.lang.RuntimeException: x is 16, but should be 10)
is 16, but should be 10)
is 16, but should be 10)

java.lang.RuntimeException: x is 16, but should be 10
    at behave_test1.steps.MySteps.thenXshouldBe(MySteps.java:21)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.jbehave.core.steps.StepCreator$ParameterisedStep.perform(StepCreator.java:550)
    at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:531)
    at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:511)
    at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:475)
    at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:308)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Failed to run story stories/my.story
java.lang.RuntimeException: x is 9, but should be 10
    at behave_test1.steps.MySteps.thenXshouldBe(MySteps.java:21)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jbehave.core.steps.StepCreator$ParameterisedStep.perform(StepCreator.java:550)
    at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:531)
    at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:511)
    at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:475)
    at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:308)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

(AfterStories)

Generating reports view to 'C:\Documents and Settings\Piotrek\IdeaProjects\jbeh1\target\jbehave' using formats '[stats, console, txt, html, xml, junitscenarioreporter]' and view properties '{defaultFormats=stats, decorateNonHtml=true, viewDirectory=view, decorated=ftl/jbehave-report-decorated.ftl, reports=ftl/jbehave-reports-with-totals.ftl, maps=ftl/jbehave-maps.ftl, navigator=ftl/jbehave-navigator.ftl, views=ftl/jbehave-views.ftl, nonDecorated=ftl/jbehave-report-non-decorated.ftl}'
Reports view generated with 2 stories (of which 0 pending) containing 6 scenarios (of which 0 pending)
Failures in reports view: 4 scenarios failed

And with tests shown:

**Comment by skurlow** [comment]
It is recommended to not run using multiple threads if you look at the Enabling section of the wiki. It is suggested to use JUnitReportingRunner.recommendedControls() which sets single threaded behaviour:

```
public static EmbedderControls recommendedControls(Embedder embedder) {
    return embedder.embedderControls()
    // don't throw an exception on generating reports for failing stories
            .doIgnoreFailureInView(true)
            // don't throw an exception when a story failed
            .doIgnoreFailureInStories(true)
            // .doVerboseFailures(true)
            .useThreads(1);
}
```

**Comment by nasalp** [comment]
Ok, but I thought specification says that a single .story is always executed by one thread, so it should't be an issue here. All displayed tests are part of the same story.
